---
title: "MRC"
subtitle: "Fun"
author: "Yihui Xie"
date: "2018/2/27"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
#xaringan::inf_mr() to create 

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

```{r}
#install packages
library(untidydata)
library(xaringan)
library(plot3D)

library(tidyverse)
```

```{r}
str(language_diversity)
```

#My Data

- Hello again

---

```{r}
ld <- language_diversity %>%
  filter(., Continent =='Africa')  %>% 
  spread(., Measurement, Value) %>% 
  select(., country = Country, pop = Population, area = Area, lang = Langs) %>% 
  mutate(., logArea = log(area), 
            logPop = log(pop))
```
---

```{r}
ld %>% 
  ggplot(., aes(x = logArea, y =lang, label = country )) +
  geom_text()
```

---

# to see the difference 

```{r}
ld %>% 
  ggplot(., aes(x = logArea, y =lang, color = logArea )) +
  geom_point()
```
---

# Fit model (MRC, 3 PARAGRAMS) include the interaction * 
# all of the possible interactions
```{r}
my_mod <- lm(lang ~ logPop + logArea, data = ld)
my_int <- lm(lang ~ logPop + logArea + logPop:logArea, data = ld)


my_int <- lm(lang ~ logPop * logArea, data = ld)
```
---












   
